---
- hosts: loadbalancers
  become: true
  tasks:
  - name: update apt cache 
    apt:
        update_cache: yes
        cache_valid_time: 3600

  - name: install haproxy
    apt:
        name: haproxy
        state: latest

  - name: copy configuration
    template:
       src: haproxy.cfg.j2
       dest: haproxy.cfg
