---
- hosts: all
  become: true
  tasks:
  - name: Install nmap, mc and aircrack-ng
    apt:
      name: 
        - nmap
        - mc
        - aircrack-ng
        - cmatrix
        - traceroute
        - lynx
      update_cache: yes
      state: latest

  - name: Copy vimrc file for vim
    template:
      src: vimrc.j2
      dest: /home/ubuntu/.vimrc
      owner: ubuntu
      group: ubuntu
