---
- hosts: loadbalancers
  become: yes
  tasks:
  - name: update apt cache
    apt:
        update_cache: yes
        cache_valid_time: 3600

  - name: install keepalived
    apt:
        name: keepalived
        state: latest

  - name: copy configuration keepalived
    template:
       src: keepalived.conf.j2
       dest: /etc/keepalived/keepalived.conf
